import { test, expect } from "@playwright/test";

/**
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 *  📊 qapulsesk-report — DEMO FILE
 *  QA Pulse by SK · www.skakarh.com
 *  npm: https://www.npmjs.com/package/qapulsesk-report
 *
 *  This file demonstrates what qapulsesk-report generates.
 *  It is NOT wired as a reporter here — the reporter is configured in
 *  playwright.config.ts and runs automatically after every test run.
 *
 *  PURPOSE OF THIS SPEC:
 *  Run a realistic mix of passing + failing tests so the generated
 *  qapulse-report/qapulse-report.html shows a real, impressive dashboard.
 *
 *  After running this file, open:
 *    qapulse-report/qapulse-report.html
 *
 *  What you will see:
 *    ✅ Dark-theme branded HTML report
 *    ✅ Pass rate ring with percentage
 *    ✅ Stats: passed / failed / skipped / duration
 *    ✅ Visual pass/fail progress bar
 *    ✅ Trend chart (if run more than once — history is enabled)
 *    ✅ Failed tests section — clickable rows show error details
 *    ✅ All suites with expandable test rows
 *    ✅ "Generated by QAPulse by SK" footer
 *
 *  Run this file:
 *    npx playwright test tests/packages/report.demo.spec.ts --project=chromium
 *
 *  Then open the report:
 *    open qapulse-report/qapulse-report.html
 *
 * ═══════════════════════════════════════════════════════════════════════════════
 */

// ─── Suite 1: E2E Tests (mostly passing) ─────────────────────────────────────
test.describe("E2E — the-internet.herokuapp.com", () => {
  test("home page loads successfully ✅", async ({ page }) => {
    await page.goto("https://the-internet.herokuapp.com");
    await expect(page).toHaveTitle("The Internet");
  });

  test("login with valid credentials ✅", async ({ page }) => {
    await page.goto("https://the-internet.herokuapp.com/login");
    await page.fill("#username", "tomsmith");
    await page.fill("#password", "SuperSecretPassword!");
    await page.click("button[type='submit']");
    await expect(page.locator("#flash")).toContainText("You logged into a secure area");
  });

  test("logout after login ✅", async ({ page }) => {
    await page.goto("https://the-internet.herokuapp.com/login");
    await page.fill("#username", "tomsmith");
    await page.fill("#password", "SuperSecretPassword!");
    await page.click("button[type='submit']");
    await page.click("a[href='/logout']");
    await expect(page.locator("#flash")).toContainText("You logged out");
  });

  test("navigation links are present on home page ✅", async ({ page }) => {
    await page.goto("https://the-internet.herokuapp.com");
    const linkCount = await page.locator("ul li a").count();
    expect(linkCount).toBeGreaterThan(10);
  });

  test("checkboxes page works correctly ✅", async ({ page }) => {
    await page.goto("https://the-internet.herokuapp.com/checkboxes");
    await page.locator("input[type='checkbox']").first().check();
    await expect(page.locator("input[type='checkbox']").first()).toBeChecked();
  });

  test("dynamic loading shows content ✅", async ({ page }) => {
    await page.goto("https://the-internet.herokuapp.com/dynamic_loading/1");
    await page.click("button");
    await expect(page.locator("#finish h4")).toBeVisible({ timeout: 10000 });
  });

  test("javascript alerts — accept ✅", async ({ page }) => {
    await page.goto("https://the-internet.herokuapp.com/javascript_alerts");
    page.on("dialog", dialog => dialog.accept());
    await page.click("button[onclick='jsAlert()']");
    await expect(page.locator("#result")).toContainText("You successfully clicked an alert");
  });

  // ─── Intentional failure — shows the report's failure display ───────────────
  test("❌ INTENTIONAL DEMO FAILURE — shows error details in report", async ({ page }) => {
    await page.goto("https://the-internet.herokuapp.com/login");
    // This intentionally fails to demonstrate how qapulsesk-report
    // displays errors — click the row in the report to see the error detail
    await expect(page.locator("#flash")).toContainText(
      "This text does not exist — intentional failure for demo",
      { timeout: 3000 }
    );
  });
});

// ─── Suite 2: API Tests (all passing) ────────────────────────────────────────
test.describe("API — jsonplaceholder.typicode.com", () => {
  test("GET /posts returns 100 posts ✅", async ({ request }) => {
    const res = await request.get("https://jsonplaceholder.typicode.com/posts");
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body).toHaveLength(100);
  });

  test("GET /posts/1 returns correct post ✅", async ({ request }) => {
    const res  = await request.get("https://jsonplaceholder.typicode.com/posts/1");
    const body = await res.json();
    expect(res.status()).toBe(200);
    expect(body.id).toBe(1);
    expect(body.userId).toBe(1);
    expect(typeof body.title).toBe("string");
  });

  test("POST /posts creates new post ✅", async ({ request }) => {
    const res  = await request.post("https://jsonplaceholder.typicode.com/posts", {
      data: { userId: 1, title: "QA Pulse by SK Demo", body: "Test post" },
    });
    const body = await res.json();
    expect(res.status()).toBe(201);
    expect(body).toHaveProperty("id");
  });

  test("DELETE /posts/1 succeeds ✅", async ({ request }) => {
    const res = await request.delete("https://jsonplaceholder.typicode.com/posts/1");
    expect(res.status()).toBe(200);
  });

  test("GET /users returns user list ✅", async ({ request }) => {
    const res  = await request.get("https://jsonplaceholder.typicode.com/users");
    const body = await res.json();
    expect(res.status()).toBe(200);
    expect(body.length).toBeGreaterThan(0);
  });
});

// ─── Suite 3: Performance Tests ───────────────────────────────────────────────
test.describe("Performance — Page Load Times", () => {
  test("home page loads under 5s ✅", async ({ page }) => {
    const start = Date.now();
    await page.goto("https://the-internet.herokuapp.com");
    const duration = Date.now() - start;
    expect(duration).toBeLessThan(5000);
    console.log(`  ⏱️  Home page: ${duration}ms`);
  });

  test("login page loads under 5s ✅", async ({ page }) => {
    const start = Date.now();
    await page.goto("https://the-internet.herokuapp.com/login");
    const duration = Date.now() - start;
    expect(duration).toBeLessThan(5000);
    console.log(`  ⏱️  Login page: ${duration}ms`);
  });

  test("API response under 2s ✅", async ({ request }) => {
    const start    = Date.now();
    await request.get("https://jsonplaceholder.typicode.com/posts/1");
    const duration = Date.now() - start;
    expect(duration).toBeLessThan(2000);
    console.log(`  ⏱️  API response: ${duration}ms`);
  });
});

// ─── Suite 4: Skipped tests — shows skipped count in report ───────────────────
test.describe("Skipped — Pending Implementation", () => {
  test.skip("mobile responsiveness — coming soon", async ({ page }) => {
    // This is intentionally skipped
    await page.goto("https://the-internet.herokuapp.com");
  });

  test.skip("dark mode toggle — coming soon", async ({ page }) => {
    // This is intentionally skipped
    await page.goto("https://the-internet.herokuapp.com");
  });
});
